<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-1PBA745" failures="2" tests="3" name="Test(failed)" time="1.64" errors="0" timestamp="2021-12-02T21:03:22 IST">
  <testcase classname="TestNgXMLStudy.FailedTestcases" name="tC2" time="1.029">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNgXMLStudy.FailedTestcases.tC2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNgXMLStudy.FailedTestcases.tC2() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- tC2 -->
  <testcase classname="TestNgXMLStudy.failedtestcasessample" name="tC4" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNgXMLStudy.failedtestcasessample.tC4(failedtestcasessample.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tC4 -->
  <testcase classname="TestNgXMLStudy.failedtestcasessample" name="tC2" time="0.506"/>
  <testcase classname="TestNgXMLStudy.FailedTestcases" name="tC1" time="0.0">
    <ignored/>
  </testcase> <!-- tC1 -->
  <testcase classname="TestNgXMLStudy.FailedTestcases" name="tC3" time="0.0">
    <ignored/>
  </testcase> <!-- tC3 -->
  <testcase classname="TestNgXMLStudy.FailedTestcases" name="tC4" time="0.0">
    <ignored/>
  </testcase> <!-- tC4 -->
  <testcase classname="TestNgXMLStudy.failedtestcasessample" name="tC1" time="0.0">
    <ignored/>
  </testcase> <!-- tC1 -->
  <testcase classname="TestNgXMLStudy.failedtestcasessample" name="tC3" time="0.0">
    <ignored/>
  </testcase> <!-- tC3 -->
</testsuite> <!-- Test(failed) -->
